package udemy.fausto.com.t_recyclerc.Model

class DataService {
    val persons : List<Person> = listOf(
        Person("Fausto", "60", "perro1"),
        Person("Nacho", "45", "perro2"),
        Person("Félix", "58", "perro3"),
        Person("Nacho", "45", "perro4"),
        Person("Aurelia", "60", "perro5"),
        Person("Juan", "16", "perro6"),
        Person("Carlos", "27", "perro7"),
        Person("Juani", "84", "perro8"),
        Person("Paco", "60", "perro9"),
        Person("David", "61", "perro4"),
        Person("Roberto", "40", "perro5"),
        Person("Fausto", "60", "perro1"),
        Person("Nacho", "45", "perro2"),
        Person("Félix", "58", "perro3"),
        Person("Nacho", "45", "perro4"),
        Person("Aurelia", "60", "perro5"),
        Person("Juan", "16", "perro6"),
        Person("Carlos", "27", "perro7"),
        Person("Juani", "84", "perro8"),
        Person("Paco", "60", "perro9"),
        Person("David", "61", "perro4"),
        Person("Roberto", "40", "perro5"),
        Person("Fausto", "60", "perro1"),
        Person("Nacho", "45", "perro2"),
        Person("Félix", "58", "perro3"),
        Person("Nacho", "45", "perro4"),
        Person("Aurelia", "60", "perro5"),
        Person("Juan", "16", "perro6"),
        Person("Carlos", "27", "perro7"),
        Person("Juani", "84", "perro8"),
        Person("Paco", "60", "perro9"),
        Person("David", "61", "perro4"),
        Person("Roberto", "40", "perro5"),
        Person("Fausto", "60", "perro1"),
        Person("Nacho", "45", "perro2"),
        Person("Félix", "58", "perro3"),
        Person("Nacho", "45", "perro4"),
        Person("Aurelia", "60", "perro5"),
        Person("Juan", "16", "perro6"),
        Person("Carlos", "27", "perro7"),
        Person("Juani", "84", "perro8"),
        Person("Paco", "60", "perro9"),
        Person("David", "61", "perro4"),
        Person("Roberto", "40", "perro5"),
        Person("Fausto", "60", "perro1"),
        Person("Nacho", "45", "perro2"),
        Person("Félix", "58", "perro3"),
        Person("Nacho", "45", "perro4"),
        Person("Aurelia", "60", "perro5"),
        Person("Juan", "16", "perro6"),
        Person("Carlos", "27", "perro7"),
        Person("Juani", "84", "perro8"),
        Person("Paco", "60", "perro9"),
        Person("David", "61", "perro4"),
        Person("Roberto", "40", "perro5"),
        Person("Fausto", "60", "perro1"),
        Person("Nacho", "45", "perro2"),
        Person("Félix", "58", "perro3"),
        Person("Nacho", "45", "perro4"),
        Person("Aurelia", "60", "perro5"),
        Person("Juan", "16", "perro6"),
        Person("Carlos", "27", "perro7"),
        Person("Juani", "84", "perro8"),
        Person("Paco", "60", "perro9"),
        Person("David", "61", "perro4"),
        Person("Roberto", "40", "perro5"),
        Person("Carlos", "27", "perro7"),
        Person("Juani", "84", "perro8"),
        Person("Paco", "60", "perro9"),
        Person("David", "61", "perro4"),
        Person("Roberto", "40", "perro5"),
        Person("Fausto", "60", "perro1"),
        Person("Nacho", "45", "perro2"),
        Person("Félix", "58", "perro3"),
        Person("Nacho", "45", "perro4"),
        Person("Aurelia", "60", "perro5"),
        Person("Juan", "16", "perro6"),
        Person("Carlos", "27", "perro7"),
        Person("Juani", "84", "perro8"),
        Person("Paco", "60", "perro9"),
        Person("David", "61", "perro4"),
        Person("Roberto", "40", "perro5")


    )


}

