package udemy.fausto.com.t_recyclerc.Model

class DataService {
    val persons : List<Person> = listOf(
        Person("60", "Fausto"),
        Person("Nacho", "45"),
        Person("Félix", "58"),
        Person("Nacho", "45"),
        Person("Aurelia", "60"),
        Person("Juan", "16"),
        Person("Carlos", "27"),
        Person("Juani", "84"),
        Person("Paco", "60"),
        Person("David", "61"),
        Person("Roberto", "40"),
        Person("Fausto", "60"),
        Person("Félix", "58"),
        Person("Nacho", "45"),
        Person("Aurelia", "60"),
        Person("Juan", "16"),
        Person("Carlos", "27"),
        Person("Juani", "84"),
        Person("Paco", "60"),
        Person("David", "61"),
        Person("Roberto", "40"),
        Person("Fausto", "60"),
        Person("Félix", "58"),
        Person("Nacho", "45"),
        Person("Aurelia", "60"),
        Person("Juan", "16"),
        Person("Carlos", "27"),
        Person("Juani", "84"),
        Person("Paco", "60"),
        Person("David", "61"),
        Person("Roberto", "40"),
        Person("Fausto", "60"),
        Person("Félix", "58"),
        Person("Nacho", "45"),
        Person("Aurelia", "60"),
        Person("Juan", "16"),
        Person("Carlos", "27"),
        Person("Juani", "84"),
        Person("Paco", "60"),
        Person("David", "61"),
        Person("Roberto", "40"),
        Person("Fausto", "60"),
        Person("Félix", "58"),
        Person("Nacho", "45"),
        Person("Aurelia", "60"),
        Person("Juan", "16"),
        Person("Carlos", "27"),
        Person("Juani", "84"),
        Person("Paco", "60"),
        Person("David", "61"),
        Person("Roberto", "40"),
        Person("Fausto", "60"),
        Person("Félix", "58"),
        Person("Nacho", "45"),
        Person("Aurelia", "60"),
        Person("Juan", "16"),
        Person("Carlos", "27"),
        Person("Juani", "84"),
        Person("Paco", "60"),
        Person("David", "61"),
        Person("Roberto", "40"),
        Person("Fausto", "60"),
        Person("Félix", "58"),
        Person("Nacho", "45"),
        Person("Aurelia", "60"),
        Person("Juan", "16"),
        Person("Carlos", "27"),
        Person("Juani", "84"),
        Person("Paco", "60"),
        Person("David", "61"),
        Person("Roberto", "40"),
        Person("Fausto", "60"),
        Person("Félix", "58"),
        Person("Nacho", "45"),
        Person("Aurelia", "60"),
        Person("Juan", "16"),
        Person("Carlos", "27"),
        Person("Juani", "84"),
        Person("Paco", "60"),
        Person("David", "61"),
        Person("Roberto", "40"),
        Person("Fausto", "60"),
        Person("Félix", "58"),
        Person("Nacho", "45"),
        Person("Aurelia", "60"),
        Person("Juan", "16"),
        Person("Carlos", "27"),
        Person("Juani", "84"),
        Person("Paco", "60"),
        Person("David", "61"),
        Person("Roberto", "40")


    )


}

